trigger:
  branches:
    include: [main]

resources:
  pipelines:
    - pipeline: infraPipeline
      source: news-app-infra
      trigger: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: 'stg'
  azureServiceConnection: 'AzureServiceConnection'
  staticAppName: 'news-app-stg-ui'

steps:
  - checkout: self

  - download: infraPipeline
    artifact: tfoutputs
    displayName: 'Download infra outputs artifact'

  - script: |
      WEBAPP_HOST=$(jq -r .webapp_default_hostname.value $(Pipeline.Workspace)/infraPipeline/tfoutputs/tfoutputs.json)
      echo "Backend hostname: $WEBAPP_HOST"
      echo "##vso[task.setvariable variable=backendUrl;issecret=false]https://$WEBAPP_HOST"
    displayName: 'Parse backend URL from infra outputs'

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'

  - script: |
      npm ci
      echo "Building frontend with API URL: $(backendUrl)"
      VITE_API_URL="$(backendUrl)" npm run build
    displayName: 'Build React (Vite) app'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: 'dist'
      action: 'upload'
      azure_static_web_apps_api_token: '$(StaticWebAppDeploymentToken)'
    displayName: 'Deploy to Azure Static Web Apps'
