name: PR Deploy and Test (Staging)
run-name: ${{ github.actor }} is deploying to Staging 🚀

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run functional/unit tests
        run: npm t

  build-deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL_STAGING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
      - name: Check API URL (debug)
        run: echo "VITE_API_URL = $VITE_API_URL"
      - name: Build Project
        run: npm run build
      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --site ${{ secrets.NETLIFY_SITE_ID_STAGING }} \
            --dir=dist \
            --prod \
            --json
