name: PR Deploy and Test (Staging)
run-name: ${{ github.actor }} is deploying to Staging 🚀

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run functional/unit tests
        run: npm t

  build-deploy:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: test
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL_STAGING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --site ${{ secrets.NETLIFY_SITE_ID_STAGING }} \
            --dir=dist \
            --prod \
            --json

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build-deploy
    env:
      ENV: staging
      BASE_URL: ${{ secrets.BASE_URL_STAGING }}
      VITE_API_URL: ${{ secrets.VITE_API_URL_STAGING }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci --force
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
